### ISSUE TITLE
`SocketException` thrown when running demo under Linux

### ISSUE THREAD

**Issue by bazwilliams** [drozhkov/upnp-clr#1]
Looks like setting the `Ttl` property of the socket created in `UpnpClient` is failing with a `SocketException` and states `Operation not supported`. 

By commenting out line 113 of `src/upnp-clr-client/UpnpClient.cs` the demo works fine. 

```
> dotnet --version
2.0.0
> uname -a
Linux PC971 4.14.0-1-amd64 #1 SMP Debian 4.14.2-1 (2017-11-30) x86_64 GNU/Linux
```

I've pulled the source code, compiled using `dotnet publish src/upnp-clr-demo` then `dotnet src/upnp-clr-demo/bin/Debug/netcoreapp2.0/upnp-clr-demo.dll`

```System.AggregateException: One or more errors occurred. (Operation not supported) ---> System.Net.Sockets.SocketException: Operation not supported
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.set_Ttl(Int16 value)
   at AmberSystems.UPnP.UpnpClient.<>c__DisplayClass2_0.<<Discover>b__4>d.MoveNext() in /home/barryw/Projects/upnp-clr/src/upnp-clr-client/UpnpClient.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AmberSystems.UPnP.UpnpClient.<Discover>d__2.MoveNext() in /home/barryw/Projects/upnp-clr/src/upnp-clr-client/UpnpClient.cs:line 156
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at AmberSystems.UPnP.Demo.Program.Main(String[] args) in /home/barryw/Projects/upnp-clr/src/upnp-clr-demo/Program.cs:line 31
---> (Inner Exception #0) System.Net.Sockets.SocketException (0x80004005): Operation not supported
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.set_Ttl(Int16 value)
   at AmberSystems.UPnP.UpnpClient.<>c__DisplayClass2_0.<<Discover>b__4>d.MoveNext() in /home/barryw/Projects/upnp-clr/src/upnp-clr-client/UpnpClient.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AmberSystems.UPnP.UpnpClient.<Discover>d__2.MoveNext() in /home/barryw/Projects/upnp-clr/src/upnp-clr-client/UpnpClient.cs:line 156<---

press any key...
```

**Comment by drozhkov** [comment]
hi,
seems to be IPv6 problem
try the fix please

**Comment by bazwilliams** [comment]
Apologies for the delay in reply, your change works absolutely fine. Could you publish an updated nuget package please? 

Thanks! 👍

**Comment by drozhkov** [comment]
done
https://www.nuget.org/packages/upnp-clr-client/0.0.2.1
